<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>pro.shushi.oinone</groupId>
        <artifactId>oinone-backend-tutorials</artifactId>
        <version>7.2.0-SNAPSHOT</version>
    </parent>
    <groupId>pro.shushi.oinone.tutorials</groupId>
    <artifactId>oinone-tutorials-boot</artifactId>
    <packaging>jar</packaging>

    <properties>
        <lettuce.version>6.3.2.RELEASE</lettuce.version>
        <commons-pool2.version>2.12.1</commons-pool2.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>pro.shushi.pamirs</groupId>
            <artifactId>a</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.boot</groupId>
            <artifactId>pamirs-boot-standard</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.boot</groupId>
            <artifactId>pamirs-distribution-id</artifactId>
        </dependency>

        <!-- rocketmq -->
        <dependency>
            <groupId>pro.shushi.pamirs.framework</groupId>
            <artifactId>pamirs-connectors-event-rocketmq</artifactId>
        </dependency>

        <!-- mysql -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <!-- distribution -->
        <dependency>
            <groupId>pro.shushi.pamirs.distribution</groupId>
            <artifactId>pamirs-distribution-faas</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.distribution</groupId>
            <artifactId>pamirs-distribution-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.distribution</groupId>
            <artifactId>pamirs-distribution-session</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.distribution</groupId>
            <artifactId>pamirs-distribution-session-cd</artifactId>
        </dependency>

        <!-- expression -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-expression-core</artifactId>
        </dependency>

        <!-- resource -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-resource-core</artifactId>
        </dependency>

        <!-- user, business, management_center -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-user-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-user-view</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-business-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-business-view</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-management-center</artifactId>
        </dependency>

        <!-- message -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-message-core</artifactId>
        </dependency>

        <!-- file -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-file2-core</artifactId>
        </dependency>

        <!-- trigger -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-trigger-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-trigger-bridge-tbschedule</artifactId>
        </dependency>

        <!-- eip -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-eip2-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-eip2-view</artifactId>
        </dependency>

        <!-- translate -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-translate</artifactId>
        </dependency>

        <!-- apps -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-apps-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-apps-view</artifactId>
        </dependency>

        <!-- sys_setting -->
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-sys-setting-core</artifactId>
        </dependency>
        <dependency>
            <groupId>pro.shushi.pamirs.core</groupId>
            <artifactId>pamirs-sys-setting-view</artifactId>
        </dependency>

        <dependency>
            <groupId>pro.shushi.pamirs.framework</groupId>
            <artifactId>pamirs-connectors-data-api</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>redis.clients</groupId>
                    <artifactId>jedis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>${lettuce.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>${commons-pool2.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/webapp</directory>
                <!--注意此次必须要放在此目录下才能被访问到-->
                <targetPath>META-INF/resources</targetPath>
                <includes>
                    <include>**/**</include>
                </includes>
            </resource>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <includes>
                    <include>**/**</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>